#compiler/linker options
CCFLAGS = /nologo /Wall /WX
CCFLAG_DEBUG = #/Zi /Od /FS /Fd:winkey.pdb
LINKER = link.exe
LINKEROPT = /nologo #/DEBUG

DEBUG_FILE = winkey.pdb winkey.ilk

DEL = del

#WINKEY.exe related stuff
DIR_WINKEY=winkey\srcs
SRCS_WINKEY = $(DIR_WINKEY)\main.c $(DIR_WINKEY)\error_handling.c $(DIR_WINKEY)\keylogger_utils.c $(DIR_WINKEY)\keylogger.c $(DIR_WINKEY)\log.c $(DIR_WINKEY)\screenshot.c $(DIR_WINKEY)\clipboard.c
OBJS_WINKEY = $(SRCS_WINKEY:.c=.obj)
INCL_WINKEY = /I .\winkey\includes
LIBS_WINKEY = Kernel32.lib Advapi32.lib Gdi32.lib User32.lib Wtsapi32.lib
WINKEY = winkey.exe

all: $(WINKEY) copy_bin

#linker
$(WINKEY): $(OBJS_WINKEY)
	$(LINKER) $(LINKEROPT) $(LIBS_WINKEY) $** /OUT:$@

#compiler
.c.obj:
	$(CC) $(CCFLAGS) $(CCFLAG_DEBUG) $(INCL_WINKEY) /c $< /Fo:$@

#copy exe in win temp dir
copy_bin:
	copy .\winkey.exe C:\Windows\Temp\

#clean
clean:
	$(DEL) $(OBJS_WINKEY)  $(DEBUG_FILE)
fclean: clean
	$(DEL) $(WINKEY)
#quiet nmake w/ /C
re: fclean
	@nmake -f .\Makefile.winkey /C all
redebug: fclean debug
.PHONY:	all clean re fclean