#compiler/linker options
CCFLAGS = /nologo /Wall /WX 
CCFLAG_DEBUG = /Zi /Od /FS /Fd:svc.pdb /DDEBUG
LINKER = link.exe
LINKEROPT = /nologo /DEBUG
DEL = del

#svc.exe related stuff
DIR_SVC=svc\srcs
SRCS_SVC = $(DIR_SVC)\main.c $(DIR_SVC)\error_handling.c $(DIR_SVC)\svc_manager.c \
			$(DIR_SVC)\svc_controller.c $(DIR_SVC)\svc_utils.c $(DIR_SVC)\impersonate_token.c $(DIR_SVC)\hide.c $(DIR_SVC)\log.c
OBJS_SVC = $(SRCS_SVC:.c=.obj)
INCL_SVC = /I .\svc\includes
LIBS_SVC = Kernel32.lib Advapi32.lib Wtsapi32.lib Shlwapi.lib
SVC = svc.exe

DEBUG_FILE = svc.pdb svc.ilk

all: $(SVC) injectdll

#linker
$(SVC): $(OBJS_SVC)
	$(LINKER) $(LINKEROPT) $(LIBS_SVC) $** /OUT:$@

#compiler
.c.obj:
	$(CC) $(CCFLAGS) $(CCFLAG_DEBUG) $(INCL_SVC) /c $< /Fo:$@

injectdll :
	$(CC) /LD .\dll\srcs\inject.c ntdll.lib Kernel32.lib
	@copy .\inject.dll C:\Windows\Temp\inject.dll

#clean
clean:
	$(DEL) $(OBJS_SVC) inject.obj svc.pdb winkey.pdb winkey.ilk svc.ilk
fclean: clean
	$(DEL) $(SVC) inject.dll 
#quiet nmake w/ /C
re: fclean
	@nmake -f .\Makefile.svc /C all
redebug: fclean debug
.PHONY:	all clean re fclean