#compiler/linker options
CCFLAGS = /nologo /Wall /WX 
CCFLAG_DEBUG = /Zi /Od /FS /Fd:svc.pdb
LINKER = link.exe
LINKEROPT = /nologo /DEBUG
DEL = del

#svc.exe related stuff
DIR_SVC=svc\srcs
SRCS_SVC = $(DIR_SVC)\main.c $(DIR_SVC)\error_handling.c $(DIR_SVC)\svc_manager.c $(DIR_SVC)\impersonate_token.c
OBJS_SVC = $(SRCS_SVC:.c=.obj)
INCL_SVC = /I .\svc\includes
LIBS_SVC = Kernel32.lib Advapi32.lib
SVC = svc.exe

DEBUG_FILE = svc.pdb svc.ilk

all: $(SVC)

#linker
$(SVC): $(OBJS_SVC)
	$(LINKER) $(LINKEROPT) $(LIBS_SVC) $** /OUT:$@

#compiler
.c.obj:
	$(CC) $(CCFLAGS) $(CCFLAG_DEBUG) $(INCL_SVC) /c $< /Fo:$@

#clean
clean:
	$(DEL) $(OBJS_SVC)
fclean: clean
	$(DEL) $(SVC)
#quiet nmake w/ /C
re: fclean
	@nmake -f .\Makefile.svc /C all
redebug: fclean debug
.PHONY:	all clean re fclean