#compiler/linker options
CCFLAGS = /nologo /Wall /WX
CCFLAG_DEBUG = /DEBUG
LINKER = link.exe
LINKEROPT = /nologo

DEL = del

#svc.exe related stuff
DIR_SVC=svc\srcs
SRCS_SVC = $(DIR_SVC)\main.c $(DIR_SVC)\error_handling.c $(DIR_SVC)\svc_manager.c
OBJS_SVC = $(SRCS_SVC:.c=.obj)
INCL_SVC = /I .\svc\includes
LIBS_SVC =  Advapi32.lib
SVC = svc.exe

all: $(SVC)

#linker
$(SVC): $(OBJS_SVC)
	$(LINKER) $(LINKEROPT) $(LIBS_SVC) $** /OUT:$@

#compiler
.c.obj:
	$(CC) $(CCFLAGS) $(INCL_SVC) /c $< /Fo:$@

#clean
clean:
	$(DEL) $(OBJS_SVC)
fclean: clean
	$(DEL) $(SVC)
#quiet nmake w/ /C
re: fclean
	@nmake /C all
redebug: fclean debug
.PHONY:	all clean re fclean